[program:nrsmarketing-laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/nrsmarketing/artisan queue:work --queue=agents,default --sleep=1 --tries=3 --timeout=1800
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nrsmarketing-worker.log
stopwaitsecs=3600
